### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by mward25** [diath/nuklear_sfml#1]
Hey there, 
just wanted to ask if this was still maintained.

Also, if you are not planning to maintain this library, it may be a good idea to point people to https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/sfml_opengl3 or https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/sfml_opengl2 in the readme file.

Thanks

**Comment by diath** [comment]
No, I made it for a project I was working on 8 years ago and figured I'd publish it on GitHub just in case anyone else needs it, I've updated the readme now.
